#!/bin/sh

CXX=${CXX:-g++}

if [ "$1" = "clean" ]
then
	( cd `dirname $0`; rm -rf *.cxx *.snk *.so *.o *.exe *.dll ../.cs src_swig )
	exit 0
fi

path=`which mcs 2> /dev/null`

if [ $? = 0 ]
then

	# Invoke swig
	mkdir -p src_swig
	swig -c++ -I../include -csharp -dllimport libvasharp -outdir src_swig -namespace VideoAnalysis video_analysis.i || exit $?

	# Compile the wrapper
	${CXX} -fPIC -D_GNU_SOURCE ${CXXFLAGS} -c -rdynamic -pthread -I../include video_analysis_wrap.cxx || exit $?
	
	# Create the module
	${CXX} ${CXXFLAGS} -shared video_analysis_wrap.o -L../lib -lvideoanalysis -o libvasharp.so || exit $?

	# Compile the library assembly
	mcs -out:av-sharp.dll -target:library src_swig/*.cs
	# uncomment the below if you want to sign the assembly
	# sn -k mlt-sharp.snk
	# mcs -out:mlt-sharp.dll -target:library -keyfile:mlt-sharp.snk src_swig/*.cs

	# Compile the example
	#mcs -r:av-sharp.dll test.cs
	
else
	echo Mono C# compiler not installed.
	exit 1
fi
